# Generated by Django 5.0.3 on 2024-03-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_system.workoutcategory'),
        ),
    ]
